"""
build_dashboard.py
==================
Assembles the Claude Design source files (index.html + all .jsx files) into
a single self-contained `dashboard.html` that Streamlit can embed.

Run this once after you receive the project from Claude Design, AND again any
time you update the design.

Usage:
    1. Drop the Claude Design files in ./dashboard_src/  (default location):
         dashboard_src/
           index.html
           ironclad-data.js     (will be ignored — replaced by injection)
           data.jsx
           ui.jsx
           charts.jsx
           views-overview.jsx
           views-categories.jsx
           views-savings.jsx
           app.jsx
    2. Run:  python build_dashboard.py
    3. The output `dashboard.html` is written in the current directory.

The output file has a placeholder string __DATA__ where app.py injects the
JSON-serialised IRONCLAD data at runtime.
"""

from __future__ import annotations
import argparse
import re
from pathlib import Path


# Load order MUST match the original index.html. Dependencies:
#   data.jsx needs window.IRONCLAD (provided by injection)
#   ui.jsx, charts.jsx need React
#   views-*.jsx need ui/charts/data
#   app.jsx needs everything else
JSX_LOAD_ORDER = [
    "data.jsx",
    "ui.jsx",
    "charts.jsx",
    "views-overview.jsx",
    "views-categories.jsx",
    "views-savings.jsx",
    "app.jsx",
]


CDN_BLOCK = """
<script src="https://unpkg.com/react@18.3.1/umd/react.production.min.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@babel/standalone@7.29.0/babel.min.js" crossorigin="anonymous"></script>
""".strip()


def extract_head_block(index_html_text: str) -> str:
    """Pull the contents of <head>...</head> out of the index.html."""
    m = re.search(r"<head[^>]*>(.*?)</head>", index_html_text, re.DOTALL | re.IGNORECASE)
    if not m:
        raise ValueError("index.html missing <head> block")
    head_inner = m.group(1)
    # Strip out the title (we'll provide our own) and any local script src
    # tags (they won't resolve in srcdoc context).
    head_inner = re.sub(r"<title>.*?</title>", "", head_inner, flags=re.DOTALL | re.IGNORECASE)
    head_inner = re.sub(r"<script[^>]*src=['\"](?!https?:)[^'\"]*['\"][^>]*></script>",
                        "", head_inner, flags=re.IGNORECASE)
    return head_inner.strip()


def build(src_dir: Path, out_path: Path) -> None:
    if not src_dir.is_dir():
        raise FileNotFoundError(f"Source directory not found: {src_dir}")

    index_path = src_dir / "index.html"
    if not index_path.exists():
        raise FileNotFoundError(f"Missing index.html in {src_dir}")
    head_inner = extract_head_block(index_path.read_text(encoding="utf-8"))

    # Collect JSX blocks in correct order
    jsx_blocks: list[str] = []
    for fname in JSX_LOAD_ORDER:
        fpath = src_dir / fname
        if not fpath.exists():
            raise FileNotFoundError(f"Missing required source file: {fpath}")
        content = fpath.read_text(encoding="utf-8")
        # Each gets its own <script type="text/babel"> block so Babel transpiles
        # them with module-like isolation. Globals attach via Object.assign(window, …)
        # which the source already uses.
        jsx_blocks.append(f'<script type="text/babel" data-source="{fname}">\n{content}\n</script>')

    # Note: we deliberately use srcdoc-friendly markup. No DOCTYPE, no <html>/<body>
    # wrappers are strictly required for components.html() but including them
    # matches the original design's font-loading expectations.
    output = f"""<!--
  dashboard.html — auto-generated by build_dashboard.py
  =====================================================
  Source files were concatenated from ./dashboard_src/. Do NOT edit by hand —
  edit the source files and re-run build_dashboard.py.

  The literal string __DATA__ below is replaced at runtime by app.py with a
  JSON dump of the pipeline output (see dashboard_export.py for the shape).
-->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Spend Diagnostic Dashboard</title>
{head_inner}
</head>
<body>
<div id="root"></div>

{CDN_BLOCK}

<script>
  // === Pipeline data injection point ===
  // app.py replaces __DATA__ with the JSON dump of the IRONCLAD-shaped dict
  // produced by dashboard_export.build_ironclad_data().
  window.IRONCLAD = __DATA__;
</script>

{chr(10).join(jsx_blocks)}

</body>
</html>
"""
    out_path.write_text(output, encoding="utf-8")
    size_kb = len(output) / 1024
    print(f"✅ Built {out_path.name} ({size_kb:.1f} KB) from {len(JSX_LOAD_ORDER)} JSX files")


def main():
    parser = argparse.ArgumentParser(description="Assemble the Claude Design dashboard into a single HTML file.")
    parser.add_argument("--src", default="dashboard_src",
                        help="Directory containing the Claude Design source files (default: ./dashboard_src)")
    parser.add_argument("--out", default="dashboard.html",
                        help="Output path (default: ./dashboard.html)")
    args = parser.parse_args()
    build(Path(args.src), Path(args.out))


if __name__ == "__main__":
    main()
